language: php

sudo: false

notifications:
    email:
        recipients:
            - dev@dmk-ebusiness.de
        on_success: change
        on_failure: always

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env:
              - TYPO3_VERSION="typo3/cms=^7.6"
        - php: 7.0
          env:
              - TYPO3_VERSION="typo3/cms=^7.6"
        - php: 7.1
          env:
              - TYPO3_VERSION="typo3/cms=^7.6"
        - php: 7.2
          env:
              - TYPO3_VERSION="typo3/cms=^7.6"
        - php: 7.0
          env:
              - TYPO3_VERSION="typo3/cms=^8.7"
        - php: 7.1
          env:
              - TYPO3_VERSION="typo3/cms=^8.7"
        - php: 7.2
          env:
              - TYPO3_VERSION="typo3/cms=^8.7"
        - php: 7.3
          env:
              - TYPO3_VERSION="typo3/cms=^8.7"
        - php: 7.2
          env:
              - TYPO3_VERSION="typo3/minimal=^9.5"
        - php: 7.3
          env:
              - TYPO3_VERSION="typo3/minimal=^9.5"
        - php: 7.2
          env:
              - TYPO3_VERSION="typo3/minimal=^10"
        - php: 7.3
          env:
              - TYPO3_VERSION="typo3/minimal=^10"
    allow_failures:
        - php: 7.2
          env:
              - TYPO3_VERSION="typo3/minimal=^10"
        - php: 7.3
          env:
              - TYPO3_VERSION="typo3/minimal=^10"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - composer --version

before_script:
    - composer require $TYPO3_VERSION
    - git checkout composer.json
    - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
    - .Build/bin/phpunit --coverage-text --coverage-clover=coverage.clover
